package com.krainium.dexviewer;

import android.app.*;import android.animation.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.Canvas;import android.graphics.Paint;import android.graphics.Path;import android.graphics.drawable.GradientDrawable;import android.graphics.Typeface;import android.net.Uri;import android.provider.OpenableColumns;import android.database.Cursor;import android.view.*;import android.view.inputmethod.EditorInfo;import android.widget.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity {
    static final int OPEN=10,SAVE=11; int purple=Color.rgb(139,92,246), cyan=Color.rgb(34,211,238), pink=Color.rgb(244,114,182), bg=Color.rgb(6,9,18),panel=Color.rgb(17,24,39),muted=Color.rgb(148,163,184); LinearLayout root,content; TextView title,status; DexFile dex; String fileName="classes.dex"; boolean dirty;
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(bg);getWindow().setNavigationBarColor(bg);showSplash();new Handler().postDelayed(this::buildHome,2850);Uri u=getIntent().getData();String testPath=getIntent().getStringExtra("testPath");if(testPath!=null)new Handler().postDelayed(()->loadTestPath(testPath),2900);else if(u!=null)new Handler().postDelayed(()->load(u),2900);}
    TextView text(String s,int sp,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(color);v.setPadding(12,10,12,10);return v;}
    GradientDrawable shape(int color,float radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(radius);g.setStroke(1,Color.argb(70,148,163,184));return g;} GradientDrawable gradient(int a,int b,float radius){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});g.setCornerRadius(radius);g.setStroke(1,Color.argb(100,139,92,246));return g;} Button button(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(14);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(shape(Color.rgb(72,42,96),18));b.setAllCaps(false);b.setPadding(18,8,18,8);return b;}
    static final class SplashWordmark extends View {
        final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG); final Path mark=new Path(); float t=0f;
        final int violet=Color.rgb(139,92,246),cyan=Color.rgb(34,211,238),pink=Color.rgb(244,63,154),black=Color.rgb(2,3,7);
        final int[] spectrum={Color.rgb(76,29,149),Color.rgb(139,92,246),Color.rgb(236,72,153),Color.rgb(249,115,22),Color.rgb(34,211,238),Color.rgb(8,145,178),Color.rgb(99,102,241),Color.rgb(244,63,154),Color.rgb(14,165,233)};
        SplashWordmark(android.content.Context c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}
        float clamp(float v){return Math.max(0,Math.min(1,v));} float ease(float v){v=clamp(v);return 1-(1-v)*(1-v)*(1-v);}
        void play(){ValueAnimator a=ValueAnimator.ofFloat(0f,1f);a.setDuration(2550);a.setInterpolator(new android.view.animation.LinearInterpolator());a.addUpdateListener(v->{t=(float)v.getAnimatedValue();invalidate();});a.start();}
        @Override protected void onDraw(Canvas c){float w=getWidth(),h=getHeight(),cx=w/2f,cy=h*.48f;c.drawColor(black);
            float intro=ease(t/.27f), burst=clamp((t-.24f)/.38f), resolve=clamp((t-.64f)/.30f);
            if(burst>0&&burst<1){float open=ease(burst),fade=1-clamp((burst-.68f)/.32f);p.setStyle(Paint.Style.FILL);for(int i=0;i<42;i++){int col=spectrum[i%spectrum.length];float seed=((i*37)%101)/100f;float dir=(i%2==0?1:-1);float x=cx+dir*(22+seed*w*.54f)*open;float bw=3+(i%7)*2+open*10;float top=cy-h*(.06f+seed*.44f)*open,bottom=cy+h*(.06f+(1-seed)*.44f)*open;p.setColor(Color.argb((int)(210*fade),Color.red(col),Color.green(col),Color.blue(col)));p.setShadowLayer(18,0,0,col);c.drawRect(x-bw/2,top,x+bw/2,bottom,p);}p.clearShadowLayer();}
            float markAlpha=(1-clamp((t-.38f)/.27f))*(1-resolve);if(markAlpha>0){c.save();float sc=.72f+.28f*intro+burst*3.8f;c.scale(sc,sc,cx,cy);p.setStyle(Paint.Style.STROKE);p.setStrokeCap(Paint.Cap.SQUARE);p.setStrokeJoin(Paint.Join.MITER);p.setStrokeWidth(18);p.setColor(Color.argb((int)(255*markAlpha),139,92,246));p.setShadowLayer(28,0,0,violet);mark.reset();mark.moveTo(cx-48,cy-82);mark.lineTo(cx-48,cy+82);mark.cubicTo(cx+68,cy+80,cx+68,cy-80,cx-48,cy-82);c.drawPath(mark,p);p.setColor(Color.argb((int)(255*markAlpha),34,211,238));p.setShadowLayer(28,0,0,cyan);c.drawLine(cx-58,cy+88,cx+58,cy-88,p);p.clearShadowLayer();c.restore();}
            if(resolve>0){float veil=ease(resolve);p.setStyle(Paint.Style.FILL);p.setColor(Color.argb((int)(245*veil),2,3,7));c.drawRect(0,0,w,h,p);float rise=(1-ease(resolve))*24;p.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));p.setTextSize(Math.min(w*.087f,58));p.setLetterSpacing(.02f);String a="DARK",b="DEX",d=" VIEWER";float total=p.measureText(a+b+d),x=(w-total)/2,y=cy+rise;p.setColor(Color.argb((int)(255*veil),255,255,255));c.drawText(a,x,y,p);x+=p.measureText(a);p.setColor(Color.argb((int)(255*veil),244,63,154));p.setShadowLayer(16,0,0,pink);c.drawText(b,x,y,p);p.clearShadowLayer();x+=p.measureText(b);p.setColor(Color.argb((int)(255*veil),255,255,255));c.drawText(d,x,y,p);p.setLetterSpacing(0);p.setTypeface(Typeface.MONOSPACE);p.setTextSize(12);p.setColor(Color.argb((int)(190*veil),148,163,184));String by="A KRAINIUM EXPERIENCE";c.drawText(by,(w-p.measureText(by))/2,y+48,p);p.setColor(Color.argb((int)(210*veil),34,211,238));c.drawRect(w*.39f,y+72,w*(.39f+.22f*ease(resolve)),y+74,p);}
        }
    }
    void showSplash(){FrameLayout f=new FrameLayout(this);f.setBackgroundColor(Color.rgb(2,3,7));SplashWordmark logo=new SplashWordmark(this);f.addView(logo,new FrameLayout.LayoutParams(-1,-1));setContentView(f);logo.post(logo::play);}
    void buildHome(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);root.setPadding(22,16,22,12);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);title=text("DARKDEX VIEWER",21,Color.WHITE);title.setTypeface(Typeface.create(Typeface.MONOSPACE,Typeface.BOLD));TextView maker=text("KRAINIUM  /  DEX WORKSPACE",10,cyan);maker.setTypeface(Typeface.MONOSPACE);brand.addView(title);brand.addView(maker);bar.addView(brand,new LinearLayout.LayoutParams(0,-2,1));Button open=button("＋  OPEN");open.setTextColor(Color.WHITE);open.setBackground(gradient(Color.rgb(109,40,217),Color.rgb(8,145,178),40));open.setOnClickListener(v->openPicker());bar.addView(open);root.addView(bar,new LinearLayout.LayoutParams(-1,-2));status=text("  SYSTEM READY  •  NO FILE MOUNTED",12,muted);status.setTypeface(Typeface.MONOSPACE);status.setBackground(shape(Color.rgb(12,18,30),18));status.setPadding(18,15,18,15);LinearLayout.LayoutParams st=new LinearLayout.LayoutParams(-1,-2);st.setMargins(0,15,0,12);root.addView(status,st);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));showEmpty();setContentView(root);}
    void showEmpty(){content.removeAllViews();LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.VERTICAL);hero.setPadding(28,32,28,28);hero.setBackground(gradient(Color.rgb(35,20,67),Color.rgb(9,32,48),28));TextView chip=text("  DEX LAB  /  ONLINE  ",11,Color.rgb(110,231,183));chip.setTypeface(Typeface.MONOSPACE);hero.addView(chip);TextView headline=text("Inspect deeper.\nEdit with precision.",28,Color.WHITE);headline.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));headline.setPadding(10,18,10,8);hero.addView(headline);hero.addView(text("A focused mobile workspace for exploring DEX structure, strings, and raw bytecode without leaving your device.",15,Color.rgb(203,213,225)));Button browse=button("BROWSE DEVICE STORAGE   →");browse.setBackground(gradient(Color.rgb(124,58,237),Color.rgb(14,116,144),44));browse.setOnClickListener(v->openPicker());LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(0,24,0,0);hero.addView(browse,bp);content.addView(hero);content.addView(text("CAPABILITIES",12,muted));LinearLayout caps=new LinearLayout(this);caps.setOrientation(LinearLayout.HORIZONTAL);String[] labels={"01\nSTRINGS","02\nHEX PATCH","03\nINTEGRITY"};for(int i=0;i<labels.length;i++){TextView card=text(labels[i],13,i==1?pink:(i==2?cyan:Color.rgb(196,181,253)));card.setTypeface(Typeface.MONOSPACE);card.setGravity(Gravity.CENTER);card.setBackground(shape(panel,20));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,104,1);cp.setMargins(i==0?0:5,0,i==2?0:5,0);caps.addView(card,cp);}content.addView(caps);showRecent();}
    void showRecent(){android.content.SharedPreferences sp=getSharedPreferences("recent",MODE_PRIVATE);String uri=sp.getString("uri",null),recentName=sp.getString("name",null);if(uri==null)return;content.addView(text("RECENT SESSION",12,muted));Button recent=button("↗  "+(recentName==null?"Open recent DEX":recentName));recent.setBackground(shape(Color.rgb(21,30,48),24));recent.setOnClickListener(v->load(Uri.parse(uri)));content.addView(recent);}
    void openPicker(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/octet-stream","application/vnd.android.dex","*/*"}).addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,OPEN);}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;if(r==OPEN){try{getContentResolver().takePersistableUriPermission(d.getData(),Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);}catch(Exception ignored){}load(d.getData());}else if(r==SAVE)write(d.getData());}
    String name(Uri u){try(Cursor c=getContentResolver().query(u,null,null,null,null)){if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(i>=0)return c.getString(i);}}catch(Exception ignored){}return "classes.dex";}
    void loadTestPath(String path){try(FileInputStream in=new FileInputStream(path);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[65536];int n;while((n=in.read(b))>0)out.write(b,0,n);dex=new DexFile(out.toByteArray());fileName=new java.io.File(path).getName();dirty=false;render();android.util.Log.i("KrainiumE2E","LOADED "+fileName+" | "+dex.summary().replace("\n"," | "));}catch(Exception e){android.util.Log.e("KrainiumE2E","FAILED "+path,e);error("Cannot open test DEX",e.getMessage());}}
    void load(Uri u){try(InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[65536];int n;while((n=in.read(b))>0){out.write(b,0,n);if(out.size()>512*1024*1024)throw new IOException("DEX exceeds 512 MB safety limit");}dex=new DexFile(out.toByteArray());fileName=name(u);getSharedPreferences("recent",MODE_PRIVATE).edit().putString("uri",u.toString()).putString("name",fileName).apply();dirty=false;render();toast("Loaded "+fileName);}catch(Exception e){error("Cannot open DEX",e.getMessage());}}
    void render(){content.removeAllViews();title.setText("DARKDEX VIEWER");status.setText("  VERIFIED DEX  •  "+DexFile.format(dex.data.length)+"  •  READY");status.setTextColor(Color.rgb(110,231,183));LinearLayout banner=new LinearLayout(this);banner.setOrientation(LinearLayout.VERTICAL);banner.setPadding(24,22,24,20);banner.setBackground(gradient(Color.rgb(33,21,64),Color.rgb(7,43,55),25));TextView version=text("DEX "+dex.version,12,cyan);version.setTypeface(Typeface.MONOSPACE);banner.addView(version);TextView nameView=text(fileName,23,Color.WHITE);nameView.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));banner.addView(nameView);banner.addView(text(dex.classCount+" classes   "+dex.methodCount+" methods   "+dex.stringCount+" strings",13,Color.rgb(203,213,225)));content.addView(banner);LinearLayout acts=new LinearLayout(this);acts.setOrientation(LinearLayout.HORIZONTAL);String[] names={"STRINGS","HEX EDIT","EXPORT"};for(String n:names){Button b=button(n);b.setTypeface(Typeface.MONOSPACE);acts.addView(b,new LinearLayout.LayoutParams(0,62,1));if(n.startsWith("STRING"))b.setOnClickListener(v->strings());else if(n.startsWith("HEX"))b.setOnClickListener(v->hexDialog(0));else b.setOnClickListener(v->savePicker());}LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,-2);ap.setMargins(0,12,0,14);content.addView(acts,ap);content.addView(text("STRUCTURE MAP",12,muted));LinearLayout stats=new LinearLayout(this);stats.setOrientation(LinearLayout.HORIZONTAL);int[] values={dex.classCount,dex.methodCount,dex.fieldCount};String[] labs={"CLASSES","METHODS","FIELDS"};for(int i=0;i<3;i++){LinearLayout cell=new LinearLayout(this);cell.setOrientation(LinearLayout.VERTICAL);cell.setGravity(Gravity.CENTER);cell.setBackground(shape(panel,18));TextView val=text(String.format(Locale.US,"%,d",values[i]),20,i==1?pink:(i==2?cyan:Color.rgb(196,181,253)));val.setTypeface(Typeface.MONOSPACE);val.setGravity(Gravity.CENTER);cell.addView(val);TextView lab=text(labs[i],10,muted);lab.setTypeface(Typeface.MONOSPACE);lab.setGravity(Gravity.CENTER);cell.addView(lab);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,100,1);cp.setMargins(i==0?0:4,0,i==2?0:4,0);stats.addView(cell,cp);}content.addView(stats);content.addView(text("HEADER TELEMETRY",12,muted));String info="MAGIC        dex\\n"+dex.version+"\\0\nFILE SIZE    "+dex.fileSize+" bytes\nHEADER       "+dex.headerSize+" bytes\nENDIAN TAG   0x"+Integer.toHexString(dex.endianTag)+"\n\nSHA 1 and Adler32 integrity values are repaired automatically after every edit.";TextView h=text(info,13,Color.rgb(203,213,225));h.setTypeface(Typeface.MONOSPACE);h.setBackground(shape(Color.rgb(12,18,30),20));h.setPadding(22,20,22,20);content.addView(h);}
    void strings(){content.removeAllViews();Button back=button("‹ Overview");back.setOnClickListener(v->render());content.addView(back);EditText q=new EditText(this);q.setHint("Search strings");q.setTextColor(Color.WHITE);q.setHintTextColor(muted);q.setSingleLine();content.addView(q);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);Runnable fill=()->{list.removeAllViews();String needle=q.getText().toString().toLowerCase(Locale.ROOT);int shown=0;for(DexFile.Entry e:dex.strings()){if(!needle.isEmpty()&&!e.value.toLowerCase(Locale.ROOT).contains(needle))continue;TextView row=text("#"+e.index+"  @0x"+Integer.toHexString(e.offset)+"\n"+e.value,14,Color.LTGRAY);row.setBackgroundColor((shown&1)==0?panel:bg);row.setOnClickListener(v->editString(e));list.addView(row);if(++shown>=500){list.addView(text("Showing first 500 matches. Refine your search.",13,purple));break;}}if(shown==0)list.addView(text("No matching strings",16,muted));};q.setOnEditorActionListener((v,a,e)->{fill.run();return true;});Button go=button("Search");go.setOnClickListener(v->fill.run());content.addView(go,2);fill.run();}
    void editString(DexFile.Entry e){EditText input=new EditText(this);input.setText(e.value);input.setTextColor(Color.WHITE);new AlertDialog.Builder(this).setTitle("Edit string #"+e.index).setMessage("For safe in-place editing, the replacement must be exactly "+e.byteLength+" UTF-8 bytes.").setView(input).setNegativeButton("Cancel",null).setNeutralButton("View hex",(d,w)->hexDialog(e.offset)).setPositiveButton("Apply",(d,w)->{try{dex.replaceString(e,input.getText().toString());dirty=true;strings();toast("String updated; integrity repaired");}catch(Exception x){error("Edit rejected",x.getMessage());}}).show();}
    void hexDialog(int initial){LinearLayout box=new LinearLayout(this);box.setPadding(32,0,32,0);box.setOrientation(LinearLayout.VERTICAL);EditText off=new EditText(this);off.setHint("Offset, e.g. 0x70");off.setText(String.format(Locale.US,"0x%X",initial));off.setSingleLine();EditText bytes=new EditText(this);bytes.setHint("Hex bytes, e.g. 01 FF A0");bytes.setSingleLine();TextView preview=text(dex.hexWindow(initial),10,Color.LTGRAY);preview.setTypeface(Typeface.MONOSPACE);box.addView(off);box.addView(bytes);box.addView(preview,new LinearLayout.LayoutParams(-1,500));new AlertDialog.Builder(this).setTitle("Hex editor").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Apply patch",(d,w)->{try{int p=parseOffset(off.getText().toString());byte[] patch=parseHex(bytes.getText().toString());if(patch.length==0)throw new IOException("Enter at least one byte");dex.patchBytes(p,patch);dirty=true;render();toast("Patched "+patch.length+" byte(s); integrity repaired");}catch(Exception x){error("Invalid patch",x.getMessage());}}).show();}
    int parseOffset(String s){s=s.trim().toLowerCase(Locale.ROOT);return s.startsWith("0x")?Integer.parseUnsignedInt(s.substring(2),16):Integer.parseInt(s);}
    byte[] parseHex(String s)throws IOException{s=s.replaceAll("[^0-9A-Fa-f]","");if((s.length()&1)!=0)throw new IOException("Hex input must contain complete byte pairs");byte[] b=new byte[s.length()/2];for(int i=0;i<b.length;i++)b[i]=(byte)Integer.parseInt(s.substring(i*2,i*2+2),16);return b;}
    void savePicker(){if(dex==null)return;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/octet-stream").putExtra(Intent.EXTRA_TITLE,fileName.replace(".dex","-edited.dex"));startActivityForResult(i,SAVE);}
    void write(Uri u){try(OutputStream o=getContentResolver().openOutputStream(u,"w")){o.write(dex.data);o.flush();dirty=false;toast("Saved edited DEX");}catch(Exception e){error("Save failed",e.getMessage());}}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}void error(String t,String m){new AlertDialog.Builder(this).setTitle(t).setMessage(m==null?"Unknown error":m).setPositiveButton("OK",null).show();}
    @Override public void onBackPressed(){if(dex!=null&&dirty)new AlertDialog.Builder(this).setTitle("Unsaved edits").setMessage("Exit without exporting your edited DEX?").setNegativeButton("Cancel",null).setPositiveButton("Exit",(d,w)->finish()).show();else super.onBackPressed();}
}
