plugins { id 'com.android.application' }

android {
    namespace 'com.krainium.dexviewer'
    compileSdk 34

    defaultConfig {
        applicationId 'com.krainium.dexviewer'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
